@UserManagementAPI_HostAddress = http://localhost:5198

GET {{UserManagementAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST http://localhost:5198/users/
Content-Type: application/json

{
  "Id" : 3,
  "Name" : "Avish",
  "Email" : "avishcyberninja94qegmail.com"
}